### ISSUE TITLE
Tri-pathi - Weighted pool spot price calculation is incorrect

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-10-notional-judging#111]
Tri-pathi

medium

# Weighted pool spot price calculation is incorrect

## Summary
Notional calculate the spot price of Weighted pool using the balances of token. Which need to be upscaled according to the balancer but Notional doesn't.

## Vulnerability Detail
Weighted pool

```solidity
File: leveraged-vaults/contracts/vaults/balancer/BalancerSpotPrice.sol
19    function getWeightedSpotPrices(
20      bytes32 poolId,
21        address poolAddress,
22        uint256 primaryIndex,
23        uint8 primaryDecimals
24    ) external view returns (uint256[] memory balances, uint256[] memory spotPrices) {
25        (/* */, balances, /* */) = Deployments.BALANCER_VAULT.getPoolTokens(poolId);
26        // Only two token pools are supported
27        require(balances.length == 2);
28        spotPrices = new uint256[](2);
29
30        uint256[] memory weights = IWeightedPool(poolAddress).getNormalizedWeights();
31
32        // Spot price calculation is specified at the link below. Do not account for swap fees
33        // because we're using this price to compare to the oracle price and adding swap fees
34       // would unnecessarily increase the price deviation.
35        // https://docs.balancer.fi/reference/math/weighted-math.html#typescript
36        // secondaryBalance * primaryWeight * primaryDecimals 
37        // --------------------------------------------------- 
38        //          primaryBalance * secondaryWeight
39        uint256 secondaryIndex = 1 - primaryIndex;
40
41        // There is a chance of a uint256 overflow if the balances[secondaryIndex] > 10**36
42        uint256 numerator = balances[secondaryIndex] * weights[primaryIndex] * (10 ** primaryDecimals);
43        uint256 denominator = balances[primaryIndex] * weights[secondaryIndex];
44        spotPrices[secondaryIndex] = numerator / denominator; //@audit-issue here we should have upscaled spot price (in 18 decimals)
45    }
```
https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/balancer/BalancerSpotPrice.sol#L19
 - [getWeightedSpotPrices](https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/balancer/BalancerSpotPrice.sol#L19) is called to find the spot price
 - it fetches the balances and Normalized weight of token at Line 25 and 30
 - Then calculated the spot price -`Price at which first token can be exchanged for second token` without upscaling them
 - Since the pool hooks in balancer always work with upscaled balance so we need to manually upscale here for consistency [Reference](https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/BaseWeightedPool.sol#L93) before calculating any params for WeighedMath

while 
```solidity
File:pkg/pool-weighted/contracts/BaseWeightedPool.sol
    function getInvariant() public view returns (uint256) {
        (, uint256[] memory balances, ) = getVault().getPoolTokens(getPoolId());

        // Since the Pool hooks always work with upscaled balances, we manually
        // upscale here for consistency
        _upscaleArray(balances, _scalingFactors()); //@audit upscale needed like this in notional

        uint256[] memory normalizedWeights = _getNormalizedWeights();
        return WeightedMath._calculateInvariant(normalizedWeights, balances);
    }
```
https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/BaseWeightedPool.sol#L93
balancer recommend to upscale the balances for the consistence calculation throughout the WeightedMath

Hence this return unscaled spot price which can create further integration risk when decimals of tokens aren't same and not 18.
## Impact
Notional returns unscaled spot price for Weighted Pool which further leads to integration and an array of issues which is dependent on the spot price of Weighted Pool
## Code Snippet
https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/balancer/BalancerSpotPrice.sol#L19
https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/BaseWeightedPool.sol#L93

## Tool used

Manual Review

## Recommendation
return upscaled spot price in Weighted pool like the composable pool

**Comment by jeffywu** [comment]
This should be a high priority issue, the spot prices would be incorrect for weighted pools with non 18 decimal tokens.

**Comment by jeffywu** [comment]
https://github.com/notional-finance/leveraged-vaults/pull/62

**Comment by xiaoming9090** [comment]
Escalate

The report highlights that there would be a risk when decimals of tokens are not the same and not 18 decimals. However, based on my calculation using two (2) tokens of different decimals below, I do not see any error with the current implementation.

The report lacks examples showing a case where tokens of two different decimals could lead to an error in the calculation in the current implementation. Unless Watson could provide a valid example, I do not see this as a valid issue.

Also, I have taken a look at the fix in the [PR 62](https://github.com/notional-finance/leveraged-vaults/pull/62/files). The computed spot price (with tokens of two different decimals) passed into the `_calculateLPTokenValue` function before and after the new fix is the same based on my calculation. In short, the results/outcomes are the same before and after the patch. Thus, this is just a refactoring of code in PR 62.

-------

The following uses two tokens with two different decimal precisions (1e6 and 1e18) for verifying the correctness of the current implementation:

**About the `getOraclePrice` function**

```solidity
function getOraclePrice(address baseToken, address quoteToken)
```

The oracle price returned will always be denominated in `POOL_PRECISION` (1e18).

Assume that the price of one (1) ETH is worth 1950 US dollars. Note that USDC is denominated in 6 decimals, while ETH is denominated in 18 decimals.

- Calling `TradingModule.getOraclePrice(ETH, USDC)` will return $1950 \times 1e18$
- Calling `TradingModule.getOraclePrice(USDC, ETH)` will return $\frac{1}{1950} \times 1e18$

The oracle price will be used to compare against the computed spot price later within the `_calculateLPTokenValue` function 

**About the `_checkPriceAndCalculateValue` function**

Per the comment on Line 86 of the `BalancerWeightedAuraVault._checkPriceAndCalculateValue` function, the spot price returned from the `SPOT_PRICE.getWeightedSpotPrices` or `SPOT_PRICE.getComposableSpotPrices` functions should be in native decimals. This is consistent across `BalancerWeightedAuraVault` and `BalancerComposableAuraVault` implementation.

The `SPOT_PRICE.getWeightedSpotPrices` will return in native decimals, and Lines 88-90 below will convert them to `POOL_PRECISION` (1e18). One of the reasons for doing so is that within the `_calculateLPTokenValue` function, the oracle price used for comparison is denominated in `POOL_PRECISION` (1e18)

```solidity
File: BalancerWeightedAuraVault.sol
76:     function _checkPriceAndCalculateValue() internal view override returns (uint256) {
77:         (/* */, uint8[] memory decimals) = TOKENS();
78: 
79:         (uint256[] memory balances, uint256[] memory spotPrices) = SPOT_PRICE.getWeightedSpotPrices(
80:             BALANCER_POOL_ID,
81:             address(BALANCER_POOL_TOKEN),
82:             PRIMARY_INDEX(),
83:             decimals[PRIMARY_INDEX()]
84:         );
85: 
86:         // Spot prices are returned in native decimals, convert them all to POOL_PRECISION
87:         // as required in the _calculateLPTokenValue method.
88:         for (uint256 i; i < spotPrices.length; i++) {
89:             spotPrices[i] = spotPrices[i] * POOL_PRECISION() / 10 ** decimals[i];
90:         }
91: 
92:         return _calculateLPTokenValue(balances, spotPrices);
93:     }
```

```solidity
File: BalancerComposableAuraVault.sol
090:     function _checkPriceAndCalculateValue() internal view override returns (uint256) {
091:         (uint256[] memory balances, uint256[] memory spotPrices) = SPOT_PRICE.getComposableSpotPrices(
092:             BALANCER_POOL_ID,
093:             address(BALANCER_POOL_TOKEN),
094:             PRIMARY_INDEX()
095:         );
096: 
097:         // Spot prices are returned in native decimals, convert them all to POOL_PRECISION
098:         // as required in the _calculateLPTokenValue method.
099:         (/* */, uint8[] memory decimals) = TOKENS();
100:         for (uint256 i; i < spotPrices.length; i++) {
101:             spotPrices[i] = spotPrices[i] * POOL_PRECISION() / 10 ** decimals[i];
102:         }
103: 
104:         return _calculateLPTokenValue(balances, spotPrices);
105:     }
```

**Scenario 1 - Primary = ETH / Secondary = USDC**

Let the primary asset be ETH (index 0) and the secondary asset be USDC (index 1). Assume that the tokens in the pool are equally weighted for simplicity's sake (50% - 50%), and the state of the pool is as follows:

- `primaryBalance` = 10 ETH = 10 * 1e18
- `secondaryBalance` = 20000 USDC = 20000 * 1e6
- `primaryDecimals` = 1e18

```solidity
(secondaryBalance * primaryWeight * primaryDecimals) / (primaryBalance * secondaryWeight)
(20000 * 1e6 * 50% * 1e18) / (10 * 1e18 * 50%)
2000 * 1e6
```

Thus, the `spotPrices` array computed within the `getWeightedSpotPrices` will be as follows. This is denominated in native decimals. The `spotPrices[USDC] = 2000 * 1e6` means that one ETH is worth 2000 USDC. Note that it is in native precision, which is correct.

```solidity
spotPrices[0] = spotPrices[ETH] = 0
spotPrices[1] = spotPrices[USDC] = 2000 * 1e6
```

```solidity
File: BalancerSpotPrice.sol
19:     function getWeightedSpotPrices(
20:         bytes32 poolId,
21:         address poolAddress,
22:         uint256 primaryIndex,
23:         uint8 primaryDecimals
24:     ) external view returns (uint256[] memory balances, uint256[] memory spotPrices) {
25:         (/* */, balances, /* */) = Deployments.BALANCER_VAULT.getPoolTokens(poolId);
26:         // Only two token pools are supported
27:         require(balances.length == 2);
28:         spotPrices = new uint256[](2);
29: 
30:         uint256[] memory weights = IWeightedPool(poolAddress).getNormalizedWeights();
31: 
32:         // Spot price calculation is specified at the link below. Do not account for swap fees
33:         // because we're using this price to compare to the oracle price and adding swap fees
34:         // would unnecessarily increase the price deviation.
35:         // https://docs.balancer.fi/reference/math/weighted-math.html#typescript
36:         // secondaryBalance * primaryWeight * primaryDecimals 
37:         // --------------------------------------------------- 
38:         //          primaryBalance * secondaryWeight
39:         uint256 secondaryIndex = 1 - primaryIndex;
40: 
41:         // There is a chance of a uint256 overflow if the balances[secondaryIndex] > 10**36
42:         uint256 numerator = balances[secondaryIndex] * weights[primaryIndex] * (10 ** primaryDecimals);
43:         uint256 denominator = balances[primaryIndex] * weights[secondaryIndex];
44:         spotPrices[secondaryIndex] = numerator / denominator;
45:     }
```

Next, the `spotPrices` array is scaled up to `POOL_PRECISION` (1e18) at Line 89 within the `BalancerWeightedAuraVault._checkPriceAndCalculateValue` function below:

```solidity
Original Array
spotPrices[0] = spotPrices[ETH] = 0
spotPrices[1] = spotPrices[USDC] = 2000 * 1e6

Converted/Upscaled Array
spotPrices[0] = 0
spotPrices[1] = spotPrices[1] * POOL_PRECISION() / 10 ** decimals[1];
spotPrices[1] = 2000 * 1e6 * 1e18 / 1e6
spotPrices[1] = 2000 * 1e18

Final Array
spotPrices[0] = 0
spotPrices[1] = 2000 * 1e18
```

The final `spotPrice[USDC]` is `2000 * 1e18`, which is the same format or has the same decimal precision as the price returned from the `getOraclePrice` function, $1950 \times 1e18$. Thus, the comparison within the `_calculateLPTokenValue` will work as intended.

```solidity
File: BalancerWeightedAuraVault.sol
76:     function _checkPriceAndCalculateValue() internal view override returns (uint256) {
77:         (/* */, uint8[] memory decimals) = TOKENS();
78: 
79:         (uint256[] memory balances, uint256[] memory spotPrices) = SPOT_PRICE.getWeightedSpotPrices(
80:             BALANCER_POOL_ID,
81:             address(BALANCER_POOL_TOKEN),
82:             PRIMARY_INDEX(),
83:             decimals[PRIMARY_INDEX()]
84:         );
85: 
86:         // Spot prices are returned in native decimals, convert them all to POOL_PRECISION
87:         // as required in the _calculateLPTokenValue method.
88:         for (uint256 i; i < spotPrices.length; i++) {
89:             spotPrices[i] = spotPrices[i] * POOL_PRECISION() / 10 ** decimals[i];
90:         }
91: 
92:         return _calculateLPTokenValue(balances, spotPrices);
93:     }
```

**Scenario 2 - Primary = USDC / Secondary = ETH**

Let's flip the currency and verify if it is working as intended too.

Let the primary asset be USDC (index 0) and the secondary asset be ETH (index 1). Assume that the tokens in the pool are equally weighted for simplicity's sake (50% - 50%), and the state of the pool is as follows:

- `primaryBalance` = 20000 USDC = 20000 * 1e6
- `secondaryBalance` = 10 ETH = 10 * 1e18
- `primaryDecimals` = 1e6

```solidity
(secondaryBalance * primaryWeight * primaryDecimals) / (primaryBalance * secondaryWeight)
(10 * 1e18 * 50% * 1e6) / (20000 * 1e6 * 50%)
(1/2000) * 1e18
```

Next, the `spotPrices` array is scaled up to `POOL_PRECISION` (1e18) by the code here (https://github.com/sherlock-audit/2023-10-notional/tree/main/leveraged-vaults/contracts/vaults/BalancerWeightedAuraVault.sol#L89)

```solidity
Original Array
spotPrices[0] = spotPrices[USDC] = 0
spotPrices[1] = spotPrices[ETH] = (1/2000) * 1e18

Converted/Upscaled Array
spotPrices[0] = 0
spotPrices[1] = spotPrices[1] * POOL_PRECISION() / 10 ** decimals[1];
spotPrices[1] = (1/2000) * 1e18 * 1e18 / 1e18
spotPrices[1] = (1/2000) * 1e18
spotPrices[1] = (1/2000) * 1e18

Final Array
spotPrices[0] = 0
spotPrices[1] = (1/2000) * 1e18
```

The final `spotPrice[ETH]` is `(1/2000) * 1e18`, which is the same format or has the same decimal precision as the price returned from the oracle $\frac{1}{1950} \times 1e18$. Thus, the comparison within the `_calculateLPTokenValue` function will work as intended.

**Additional Note**

As shown above, the comparison between the spot price and oracle price is working as intended in the current implementation.

As far as I know, the balances only need to be scaled up if the balances are passing into `WeightedMath`'s functions. For instance, when using `WeightedMath` to compute the invariant or calling other functions within here https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/WeightedMath.sol)

Since the `SPOT_PRICE.getWeightedSpotPrices` function's purpose is to obtain the spot price in native precision and did not rely on any of the `WeightedMath`'s functions, I do not see the need to scale up. Multiple references show the method of computing the spot price of any two tokens without scaling.

- https://token-engineering-balancer.gitbook.io/balancer-simulations/additional-code-and-instructions/balancer-the-python-edition/balancer_math.py
- https://docs.balancer.fi/reference/math/weighted-math.html#spot-price

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The report highlights that there would be a risk when decimals of tokens are not the same and not 18 decimals. However, based on my calculation using two (2) tokens of different decimals below, I do not see any error with the current implementation.
> 
> The report lacks examples showing a case where tokens of two different decimals could lead to an error in the calculation in the current implementation. Unless Watson could provide a valid example, I do not see this as a valid issue.
> 
> Also, I have taken a look at the fix in the [PR 62](https://github.com/notional-finance/leveraged-vaults/pull/62/files). The computed spot price (with tokens of two different decimals) passed into the `_calculateLPTokenValue` function before and after the new fix is the same based on my calculation. In short, the results/outcomes are the same before and after the patch. Thus, this is just a refactoring of code in PR 62.
> 
> -------
> 
> The following uses two tokens with two different decimal precisions (1e6 and 1e18) for verifying the correctness of the current implementation:
> 
> **About the `getOraclePrice` function**
> 
> ```solidity
> function getOraclePrice(address baseToken, address quoteToken)
> ```
> 
> The oracle price returned will always be denominated in `POOL_PRECISION` (1e18).
> 
> Assume that the price of one (1) ETH is worth 1950 US dollars. Note that USDC is denominated in 6 decimals, while ETH is denominated in 18 decimals.
> 
> - Calling `TradingModule.getOraclePrice(ETH, USDC)` will return $1950 \times 1e18$
> - Calling `TradingModule.getOraclePrice(USDC, ETH)` will return $\frac{1}{1950} \times 1e18$
> 
> The oracle price will be used to compare against the computed spot price later within the `_calculateLPTokenValue` function 
> 
> **About the `_checkPriceAndCalculateValue` function**
> 
> Per the comment on Line 86 of the `BalancerWeightedAuraVault._checkPriceAndCalculateValue` function, the spot price returned from the `SPOT_PRICE.getWeightedSpotPrices` or `SPOT_PRICE.getComposableSpotPrices` functions should be in native decimals. This is consistent across `BalancerWeightedAuraVault` and `BalancerComposableAuraVault` implementation.
> 
> The `SPOT_PRICE.getWeightedSpotPrices` will return in native decimals, and Lines 88-90 below will convert them to `POOL_PRECISION` (1e18). One of the reasons for doing so is that within the `_calculateLPTokenValue` function, the oracle price used for comparison is denominated in `POOL_PRECISION` (1e18)
> 
> ```solidity
> File: BalancerWeightedAuraVault.sol
> 76:     function _checkPriceAndCalculateValue() internal view override returns (uint256) {
> 77:         (/* */, uint8[] memory decimals) = TOKENS();
> 78: 
> 79:         (uint256[] memory balances, uint256[] memory spotPrices) = SPOT_PRICE.getWeightedSpotPrices(
> 80:             BALANCER_POOL_ID,
> 81:             address(BALANCER_POOL_TOKEN),
> 82:             PRIMARY_INDEX(),
> 83:             decimals[PRIMARY_INDEX()]
> 84:         );
> 85: 
> 86:         // Spot prices are returned in native decimals, convert them all to POOL_PRECISION
> 87:         // as required in the _calculateLPTokenValue method.
> 88:         for (uint256 i; i < spotPrices.length; i++) {
> 89:             spotPrices[i] = spotPrices[i] * POOL_PRECISION() / 10 ** decimals[i];
> 90:         }
> 91: 
> 92:         return _calculateLPTokenValue(balances, spotPrices);
> 93:     }
> ```
> 
> ```solidity
> File: BalancerComposableAuraVault.sol
> 090:     function _checkPriceAndCalculateValue() internal view override returns (uint256) {
> 091:         (uint256[] memory balances, uint256[] memory spotPrices) = SPOT_PRICE.getComposableSpotPrices(
> 092:             BALANCER_POOL_ID,
> 093:             address(BALANCER_POOL_TOKEN),
> 094:             PRIMARY_INDEX()
> 095:         );
> 096: 
> 097:         // Spot prices are returned in native decimals, convert them all to POOL_PRECISION
> 098:         // as required in the _calculateLPTokenValue method.
> 099:         (/* */, uint8[] memory decimals) = TOKENS();
> 100:         for (uint256 i; i < spotPrices.length; i++) {
> 101:             spotPrices[i] = spotPrices[i] * POOL_PRECISION() / 10 ** decimals[i];
> 102:         }
> 103: 
> 104:         return _calculateLPTokenValue(balances, spotPrices);
> 105:     }
> ```
> 
> **Scenario 1 - Primary = ETH / Secondary = USDC**
> 
> Let the primary asset be ETH (index 0) and the secondary asset be USDC (index 1). Assume that the tokens in the pool are equally weighted for simplicity's sake (50% - 50%), and the state of the pool is as follows:
> 
> - `primaryBalance` = 10 ETH = 10 * 1e18
> - `secondaryBalance` = 20000 USDC = 20000 * 1e6
> - `primaryDecimals` = 1e18
> 
> ```solidity
> (secondaryBalance * primaryWeight * primaryDecimals) / (primaryBalance * secondaryWeight)
> (20000 * 1e6 * 50% * 1e18) / (10 * 1e18 * 50%)
> 2000 * 1e6
> ```
> 
> Thus, the `spotPrices` array computed within the `getWeightedSpotPrices` will be as follows. This is denominated in native decimals. The `spotPrices[USDC] = 2000 * 1e6` means that one ETH is worth 2000 USDC. Note that it is in native precision, which is correct.
> 
> ```solidity
> spotPrices[0] = spotPrices[ETH] = 0
> spotPrices[1] = spotPrices[USDC] = 2000 * 1e6
> ```
> 
> ```solidity
> File: BalancerSpotPrice.sol
> 19:     function getWeightedSpotPrices(
> 20:         bytes32 poolId,
> 21:         address poolAddress,
> 22:         uint256 primaryIndex,
> 23:         uint8 primaryDecimals
> 24:     ) external view returns (uint256[] memory balances, uint256[] memory spotPrices) {
> 25:         (/* */, balances, /* */) = Deployments.BALANCER_VAULT.getPoolTokens(poolId);
> 26:         // Only two token pools are supported
> 27:         require(balances.length == 2);
> 28:         spotPrices = new uint256[](2);
> 29: 
> 30:         uint256[] memory weights = IWeightedPool(poolAddress).getNormalizedWeights();
> 31: 
> 32:         // Spot price calculation is specified at the link below. Do not account for swap fees
> 33:         // because we're using this price to compare to the oracle price and adding swap fees
> 34:         // would unnecessarily increase the price deviation.
> 35:         // https://docs.balancer.fi/reference/math/weighted-math.html#typescript
> 36:         // secondaryBalance * primaryWeight * primaryDecimals 
> 37:         // --------------------------------------------------- 
> 38:         //          primaryBalance * secondaryWeight
> 39:         uint256 secondaryIndex = 1 - primaryIndex;
> 40: 
> 41:         // There is a chance of a uint256 overflow if the balances[secondaryIndex] > 10**36
> 42:         uint256 numerator = balances[secondaryIndex] * weights[primaryIndex] * (10 ** primaryDecimals);
> 43:         uint256 denominator = balances[primaryIndex] * weights[secondaryIndex];
> 44:         spotPrices[secondaryIndex] = numerator / denominator;
> 45:     }
> ```
> 
> Next, the `spotPrices` array is scaled up to `POOL_PRECISION` (1e18) at Line 89 within the `BalancerWeightedAuraVault._checkPriceAndCalculateValue` function below:
> 
> ```solidity
> Original Array
> spotPrices[0] = spotPrices[ETH] = 0
> spotPrices[1] = spotPrices[USDC] = 2000 * 1e6
> 
> Converted/Upscaled Array
> spotPrices[0] = 0
> spotPrices[1] = spotPrices[1] * POOL_PRECISION() / 10 ** decimals[1];
> spotPrices[1] = 2000 * 1e6 * 1e18 / 1e6
> spotPrices[1] = 2000 * 1e18
> 
> Final Array
> spotPrices[0] = 0
> spotPrices[1] = 2000 * 1e18
> ```
> 
> The final `spotPrice[USDC]` is `2000 * 1e18`, which is the same format or has the same decimal precision as the price returned from the `getOraclePrice` function, $1950 \times 1e18$. Thus, the comparison within the `_calculateLPTokenValue` will work as intended.
> 
> ```solidity
> File: BalancerWeightedAuraVault.sol
> 76:     function _checkPriceAndCalculateValue() internal view override returns (uint256) {
> 77:         (/* */, uint8[] memory decimals) = TOKENS();
> 78: 
> 79:         (uint256[] memory balances, uint256[] memory spotPrices) = SPOT_PRICE.getWeightedSpotPrices(
> 80:             BALANCER_POOL_ID,
> 81:             address(BALANCER_POOL_TOKEN),
> 82:             PRIMARY_INDEX(),
> 83:             decimals[PRIMARY_INDEX()]
> 84:         );
> 85: 
> 86:         // Spot prices are returned in native decimals, convert them all to POOL_PRECISION
> 87:         // as required in the _calculateLPTokenValue method.
> 88:         for (uint256 i; i < spotPrices.length; i++) {
> 89:             spotPrices[i] = spotPrices[i] * POOL_PRECISION() / 10 ** decimals[i];
> 90:         }
> 91: 
> 92:         return _calculateLPTokenValue(balances, spotPrices);
> 93:     }
> ```
> 
> **Scenario 2 - Primary = USDC / Secondary = ETH**
> 
> Let's flip the currency and verify if it is working as intended too.
> 
> Let the primary asset be USDC (index 0) and the secondary asset be ETH (index 1). Assume that the tokens in the pool are equally weighted for simplicity's sake (50% - 50%), and the state of the pool is as follows:
> 
> - `primaryBalance` = 20000 USDC = 20000 * 1e6
> - `secondaryBalance` = 10 ETH = 10 * 1e18
> - `primaryDecimals` = 1e6
> 
> ```solidity
> (secondaryBalance * primaryWeight * primaryDecimals) / (primaryBalance * secondaryWeight)
> (10 * 1e18 * 50% * 1e6) / (20000 * 1e6 * 50%)
> (1/2000) * 1e18
> ```
> 
> Next, the `spotPrices` array is scaled up to `POOL_PRECISION` (1e18) by the code here (https://github.com/sherlock-audit/2023-10-notional/tree/main/leveraged-vaults/contracts/vaults/BalancerWeightedAuraVault.sol#L89)
> 
> ```solidity
> Original Array
> spotPrices[0] = spotPrices[USDC] = 0
> spotPrices[1] = spotPrices[ETH] = (1/2000) * 1e18
> 
> Converted/Upscaled Array
> spotPrices[0] = 0
> spotPrices[1] = spotPrices[1] * POOL_PRECISION() / 10 ** decimals[1];
> spotPrices[1] = (1/2000) * 1e18 * 1e18 / 1e18
> spotPrices[1] = (1/2000) * 1e18
> spotPrices[1] = (1/2000) * 1e18
> 
> Final Array
> spotPrices[0] = 0
> spotPrices[1] = (1/2000) * 1e18
> ```
> 
> The final `spotPrice[ETH]` is `(1/2000) * 1e18`, which is the same format or has the same decimal precision as the price returned from the oracle $\frac{1}{1950} \times 1e18$. Thus, the comparison within the `_calculateLPTokenValue` function will work as intended.
> 
> **Additional Note**
> 
> As shown above, the comparison between the spot price and oracle price is working as intended in the current implementation.
> 
> As far as I know, the balances only need to be scaled up if the balances are passing into `WeightedMath`'s functions. For instance, when using `WeightedMath` to compute the invariant or calling other functions within here https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/WeightedMath.sol)
> 
> Since the `SPOT_PRICE.getWeightedSpotPrices` function's purpose is to obtain the spot price in native precision and did not rely on any of the `WeightedMath`'s functions, I do not see the need to scale up. Multiple references show the method of computing the spot price of any two tokens without scaling.
> 
> - https://token-engineering-balancer.gitbook.io/balancer-simulations/additional-code-and-instructions/balancer-the-python-edition/balancer_math.py
> - https://docs.balancer.fi/reference/math/weighted-math.html#spot-price

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Czar102** [comment]
@nevillehuang @jeffywu what do you think about the above?

**Comment by jeffywu** [comment]
@xiaoming9090 is correct, I made my initial comment on first glance but when making the fix it was apparent that the end result was the same. However, I'm not sure if scaling factors may eventually be used for other purposes (as they are in in ComposableStablePools) in WeightedPools in the future, that does seem like something Balancer might do. If so, this is slightly more future proof, perhaps.

**Comment by nevillehuang** [comment]
Agree with @jeffywu and @xiaoming9090, unless I am missing something. Have consulted watson for input.

**Comment by Czar102** [comment]
Thank you, @nevillehuang. If no counterarguments will be proposed within 24h, I will be accepting the escalation and invalidating the issue.

**Comment by Tri-pathi** [comment]
The impact isn't high because the `_checkPriceAndCalculateValue` function re-scales during comparison with the oracle price, aligning it again to 18 decimals. Furthermore, the computation logic for the spot price resides in external function hence As sponsor stated , this adjustment was crucial to ensure synchronization with Balancer and their proprietary implementation in the composable pool. Also ,This will prevent further integration risk.
Happy to see the implemented PR which solved the above problem.👍

**Comment by Czar102** [comment]
So, if I understand correctly, this would be an informational issue.
Is this right? @Tri-pathi

**Comment by Tri-pathi** [comment]
Low/informational in the current context but valid as fix was necessary

**Comment by Czar102** [comment]
Result:
Low
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-10-notional-judging/issues/111/#issuecomment-1842499605): accepted

**Comment by MLON33** [comment]
Fix: https://github.com/notional-finance/leveraged-vaults/pull/62

**Comment by xiaoming9090** [comment]
Code refactored in [PR 62](https://github.com/notional-finance/leveraged-vaults/pull/62)
