### ISSUE TITLE
shealtielanz - Use of transfer instead of call to send ETH.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#94]
shealtielanz

medium

# Use of transfer instead of call to send ETH.

## Summary
Although the use of transfer is intentional by the team, and used against reentrancy.
Use of transfer() might render ETH impossible to withdraw because after istanbul hardfork, there is an increase in the gas cost of the SLOAD operation and therefore breaks some existing smart contracts.Those contracts will break because their fallback functions used to consume less than 2300 gas, and they’ll now consume more, since 2300 the amount of gas a contract’s fallback function receives if it’s called via Solidity’s transfer() or send() methods. Any smart contract that uses transfer() or send() is taking a hard dependency on gas costs by forwarding a fixed amount of gas: 2300.
## Poc
- https://consensys.net/diligence/blog/2019/09/stop-using-soliditys-transfer-now/
- https://blog.openzeppelin.com/opyn-gamma-protocol-audit/
## Code Snippet

- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/BaseStrategyVault.sol#L201
- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/BaseStrategyVault.sol#L200
## Tool used

Manual Review

## Recommendation
Use call and and specified amount of gas to be used which can be change seasonally in a case of a fork

**Comment by nevillehuang** [comment]
Invalid, Transfer instead of call not valid based on sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid). 

> 10. Use of call vs transfer with the reasoning that the gas price may not be the same value of 2300. This will be considered as a protocol choice and would be considering this issue in the low/informational category.

Additionally, it is a known issue in contest details [here](https://github.com/sherlock-audit/2023-10-notional#q-please-list-any-known-issuesacceptable-risks-that-should-not-result-in-a-valid-finding)

> 2. Use of transfer() for ETH is well understood and used to mitigate re-entrancy.

**Comment by shealtielanz** [comment]
Escalate 

Hello @nevillehuang 
I agree with your point
> Invalid, Transfer instead of call not valid based on sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid).
_
Use of call vs transfer with the reasoning that the gas price may not be the same value of 2300. This will be considered as a protocol choice and would be considering this issue in the low/informational category.
Additionally, it is a known issue in contest details [here](https://github.com/sherlock-audit/2023-10-notional#q-please-list-any-known-issuesacceptable-risks-that-should-not-result-in-a-valid-finding)
_
Use of transfer() for ETH is well understood and used to mitigate re-entrancy.

However as my report states I am aware but call should be used with a specified gas or a non-reentrant modifier be used, 
My issue here is you tagged it as Invalid I kindly request that you tag as low or Informative rather than Invalid, even tho no reward is given for it.

thank you so much for your time again I appreciate

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> Hello @nevillehuang 
> I agree with your point
> > Invalid, Transfer instead of call not valid based on sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid).
> _
> Use of call vs transfer with the reasoning that the gas price may not be the same value of 2300. This will be considered as a protocol choice and would be considering this issue in the low/informational category.
> Additionally, it is a known issue in contest details [here](https://github.com/sherlock-audit/2023-10-notional#q-please-list-any-known-issuesacceptable-risks-that-should-not-result-in-a-valid-finding)
> _
> Use of transfer() for ETH is well understood and used to mitigate re-entrancy.
> 
> However as my report states I am aware but call should be used with a specified gas or a non-reentrant modifier be used, 
> My issue here is you tagged it as Invalid I kindly request that you tag as low or Informative rather than Invalid, even tho no reward is given for it.
> 
> thank you so much for your time again I appreciate 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@shealtielanz 

The question in the contest details explicitly mentions the following:

> Please list any known issues/acceptable risks that should not result in a valid finding.

So this should not be a valid finding. Also consider not escalating a low severity issue in the future as afaik, even if it is a valid low severity issue, sherlock will reject the escalation as low severity issues are considered invalid.

**Comment by shealtielanz** [comment]
Thanks for the advice
but you statement 
> sherlock will reject the escalation as low severity issues are considered invalid.

Is wrong
Sherlock doesn't reject the escalation as invalid as multiple issues by Sherlock to protocols have been tagged as low/info.
Examples
- https://github.com/sherlock-audit/2023-02-notional-judging/issues/16
- https://github.com/sherlock-audit/2023-02-notional-judging/issues/14
- https://github.com/sherlock-audit/2023-02-notional-judging/issues/17
- https://github.com/sherlock-audit/2023-02-notional-judging/issues/23

Your point 
> Please list any known issues/acceptable risks that should not result in a valid finding.

The protocol, are aware of the issue that the gas might not be sufficient for some calls, and are used to mitigate reentrancy.
**My report**
- A hard fork will occur breaking the contracts are gas forwarded via transfer won't be enough
- I gave a recommendation to help solve the issue with reentrancy and avoid the contracts from breaking in the case of a hard fork

Just like you pointed out on your first comment, 
> Use of call vs transfer with the reasoning that the gas price may not be the same value of 2300. This will be considered as a protocol choice and would be considering this issue in the low/informational category.

I believe that this issue is of at least low severity and kindly request the tag should be changed from invalid

**Comment by nevillehuang** [comment]
@shealtielanz 

Yes the issue would be valid if its low severity, but I think the escalation itself would be rejected if I'm not wrong, unless I am missing something. Will have @Czar102 confirm.

But I maintain my previous comment that this issue should be invalid, so I have no further inputs.

**Comment by shealtielanz** [comment]
I understand your point @nevillehuang 
However whatever guideline it is I don’t think it can be confirmed on Sherlock’s website, and I believe my escalation is valid as I stated above I would love to hear what @Czar102 thinks about this.
Thank you for your time

**Comment by Czar102** [comment]
Sherlock doesn't differentiate Low, Informational and Invalid issues. They are the same for us. We don't place Low/Info tags anymore. Also, I don't see a point of this escalation – the issue is to be disregarded anyway.
Also, fyi, there is no issue arising from higher costs of storage access opcodes because of [eip-2930](https://eips.ethereum.org/EIPS/eip-2930).
Even if I was to choose between low/info and invalid, I would choose the latter because it was explicitly mentioned in the README that this issue should not be reported. 

Planning to reject the escalation and leave the issue as is.

**Comment by shealtielanz** [comment]
Go ahead, I agree with the points stated by @nevillehuang and @Czar102.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [shealtielanz](https://github.com/sherlock-audit/2023-10-notional-judging/issues/94/#issuecomment-1838826948): rejected
