### ISSUE TITLE
squeaky_cactus - `SingleSidedLPVaultBase.emergencyExit` can be reverted by a front running withdrawal under certain conditions

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-10-notional-judging#99]
squeaky_cactus

medium

# `SingleSidedLPVaultBase.emergencyExit` can be reverted by a front running withdrawal under certain conditions

## Summary
All the leveraged vaults share the same `emergencyExit` function, inherited from their ancestor `SingleSidedLPVaultBase`.

When `SingleSidedLPVaultBase.emergencyExit` is called with the parameter `claimToExit` being the number of claims the vault holds, then a front running withdrawal transaction will cause the emergency exit to revert.

## Vulnerability Detail
When performing an emergency exit, the used parameter `claimToExit` is the amount of claims of the leveraged vault to unstake from the reward pool and exit from the LP pool.

[SingleSidedLPVaultBase.emergencyExit](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/SingleSidedLPVaultBase.sol#L480-L496)
```solidity
    function emergencyExit(
        uint256 claimToExit, bytes calldata /* data */
    ) external override onlyRole(EMERGENCY_EXIT_ROLE) {
        StrategyVaultState memory state = VaultStorage.getStrategyVaultState();
        if (claimToExit == 0) claimToExit = state.totalPoolClaim;

        // By setting min amounts to zero, we will accept whatever tokens come from the pool
        // in a proportional exit. Front running will not have an effect since no trading will
        // occur during a proportional exit.
        _unstakeAndExitPool(claimToExit, new uint256[](NUM_TOKENS()), true);

        state.totalPoolClaim = state.totalPoolClaim - claimToExit;
        state.setStrategyVaultState();

        emit EmergencyExit(claimToExit);
        _lockVault();
    }
```

When `claimToExit` is greater than the claims the vault holds, then the transaction reverts during `_unstakeAndExitPool` call with `"ERC20: burn amount exceeds balance"` from the pool.

### Steps
Let us assume one user: Alice, who holds 5 shares.

1. Emergency Exit tx created with `claimToExit` == `state.totalPoolClaim`
2. Withdrawal `one share` tx created 
3. Withdrawal tx is processed before Emergency Exit tx (front running)
4. Vault holds one less share, and the corresponding amount less claims. 
5. Emergency Exit tx is processed but reverts on `_unstakeAndExitPool`, as `claimToExit` is now greater than the vault's held claims.

### Alternative cause
To exit all funds, it most likely zero will be used as `claimToExit`, however is still a case where `state.totalPoolClaim` can be greater than the held claims, meaning you would legitimately pass in a non-zero value for `claimToExit`.

Accounting problems with either the reward or LP pools (e.g. from an exploit), would result in the claims accounted in the leveraged vaults being no longer in sync with those held by the pools, meaning `claimToExit` would be the value held by the pools, not `state.totalPoolClaim`.

### Proof of concept
A test case demonstrating `claimToExit` as the reward pool balance for the vault, using the `Curve2TokenConvexVault.sol`.

Place the following Solidity into the contract `Test_FRAX` in `FRAX_USDC_e.t.sol` and run with `forge test --match-contract Test_FRAX --match-test test_frontRunning_prevents_emergencyExit`
```solidity
    function test_frontRunning_prevents_emergencyExit() public {
        // Deal to 'account' and deposit into the vault
        address account = makeAddr("account");
        uint256 maturity = maturities[0];
        enterVaultBypass(account, maxDeposit, maturity, getDepositParams(0, 0));

        // Grant 'exit' the emergency exit role
        address exit = makeAddr("exit");
        grantEmergencyExitRole(exit);

        // Vault holdings of the reward pool
        uint256 rewardPoolClaim = rewardPool.balanceOf(address(vault));
        assertGt(0, rewardPoolClaim);

        // Front running tx - withdraw; single share, no minimum price
        exitVaultBypass(
            account,
            1,
            maturity,
            getRedeemParams(0, maturity)
        );

        // Emergency exit tx
        vm.prank(exit);
        v().emergencyExit(rewardPoolClaim, "");
        // @audit - emergency exit reverts with "Reason: ERC20: burn amount exceeds balance"
        // Cause being withdrawing more than balance from the Convex pool
        // 0xF2afB340D1B50108Bd32212e867946B5B8044c23::withdraw(988296665078543581 [9.882e17], false) [delegatecall]
    }

    function grantEmergencyExitRole(address exit) private {
        bytes32 role = v().EMERGENCY_EXIT_ROLE();
        vm.prank(NOTIONAL.owner());
        v().grantRole(role, exit);
    }
```

## Impact
Excerpt from the Discord channel [notional-update-4-nov-18](https://discord.com/channels/812037309376495636/1175450365395751023/1175781082336067655)

> Jeff Wu | Notional — 11/19/2023 10:54 PM
>
> Emergency exits are only intended to be executed during a security incident, not possible to really have a "verification" of such a thing on chain. 
> I'd expect whoever is holding this role to be working in the best interests of protecting user funds. 
> If they would be unable to fulfill that role then yes, I would say that is valid bug. 

The emergency exit function is intended to withdraw funds from the both the reward and LP pools in case of a security incident, an example could be either the LP pool or reward pool being attacked / exploited.

When the actor attempts to protect user funds by calling the emergency exit, they would believe there is a real risk for material loss of funds.
 i.e. emergency exit will not be called frivolously, but only in serious circumstances.

A situation where emergency exit is prevented from being successfully executing, leaves the user funds exposed risk of loss, 
which depending on the nature of the incident, could result in serious downside.

The cost of executing the front running attack is a single fraction of a vault share and the elevated gas price, 
and the attack is repeatable (keep funds at risk as long as necessary).

## Code Snippet
https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/SingleSidedLPVaultBase.sol#L489-L489

## Tool used
Manual Review, Forge tst

## Recommendation
`SingleSidedLPVaultBase.emergencyExit()` is only callable by a restricted role (who we may assume is acting in the best interest of the protocol).
When the input `claimToExit` is greater than the current claim the vault holds (`state.totalPoolClaim`), 
reducing the amount being claimed to the full amount of claims the vault holds will fulfill the intent of caller,
as best can be achieved in an emergency situation.

Update in [SingleSidedLPVaultBase.emergencyExit](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/SingleSidedLPVaultBase.sol#L480-L496)
```diff
    function emergencyExit(
        uint256 claimToExit, bytes calldata /* data */
    ) external override onlyRole(EMERGENCY_EXIT_ROLE) {
        StrategyVaultState memory state = VaultStorage.getStrategyVaultState();
-        if (claimToExit == 0) claimToExit = state.totalPoolClaim;
+        if (claimToExit == 0 || claimToExit > state.totalPoolClaim) claimToExit = state.totalPoolClaim;

        // By setting min amounts to zero, we will accept whatever tokens come from the pool
        // in a proportional exit. Front running will not have an effect since no trading will
        // occur during a proportional exit.
        _unstakeAndExitPool(claimToExit, new uint256[](NUM_TOKENS()), true);

        state.totalPoolClaim = state.totalPoolClaim - claimToExit;
        state.setStrategyVaultState();

        emit EmergencyExit(claimToExit);
        _lockVault();
    }
```

**Comment by jeffywu** [comment]
Agree this is a pragmatic change, not sure about the severity here.

**Comment by jeffywu** [comment]
https://github.com/notional-finance/leveraged-vaults/pull/65

**Comment by T-Woodward** [comment]
I don't fully understand this. So the auditor is saying that the Balancer pool's accounting may be wrong, which would lead the emergency exit role to call the emergency exit function with a claimToExit value that is greater than state.totalPoolClaim? And in this case, the call would fail?

It seems like the auditor is suggesting that it could be possible that broken accounting on the pool would necessitate inputting a specific claimToExit value in order to withdraw all the BPTs instead of inputting 0. 

> To exit all funds, it most likely zero will be used as claimToExit, however is still a case where state.totalPoolClaim can be greater than the held claims, meaning you would legitimately pass in a non-zero value for claimToExit.

But then the auditor's recommendation is to add a condition whereby claimToExit is eventually set to the same value as if a zero-value were passed in. This contradicts my impression of what the auditor is suggesting is the problem here.

Additionally - if the accounting really is broken on the Balancer pool, isn't it possible that we would need to set claimToExit greater than state.totalPoolClaim in order to get all our BPTs back?

**Comment by xiaoming9090** [comment]
Escalate

There are two (2) possible scenarios outlined in the report:

1) If the admin wants to withdraw all shares during an emergency, they should configure the `claimToExit` to zero as per the source code's comment at Line 479 below. If the admin wants to withdraw all shares but chooses not to set the `claimToExit` to zero and results in undesirable consequences, it is considered an admin input error and should not be considered a valid Medium/High.

```solidity
File: SingleSidedLPVaultBase.sol
475:     /// @notice Allows the emergency exit role to trigger an emergency exit on the vault.
476:     /// In this situation, the `claimToExit` is withdrawn proportionally to the underlying
477:     /// tokens and held on the vault. The vault is locked so that no entries, exits or
478:     /// valuations of vaultShares can be performed.
479:     /// @param claimToExit if this is set to zero, the entire pool claim is withdrawn
480:     function emergencyExit(
481:         uint256 claimToExit, bytes calldata /* data */
482:     ) external override onlyRole(EMERGENCY_EXIT_ROLE) {
```

2) Following is the extract from the report:

> To exit all funds, it most likely zero will be used as `claimToExit`, however is still a case where `state.totalPoolClaim` can be greater than the held claims, meaning you would legitimately pass in a non-zero value for `claimToExit`.
>
> Accounting problems with either the reward or LP pools (e.g. from an exploit), would result in the claims accounted in the leveraged vaults being no longer in sync with those held by the pools, meaning `claimToExit` would be the value held by the pools, not `state.totalPoolClaim`.

It stated that this would be an issue if there were an accounting problem within Notional's leverage vault that could result in a case where the `state.totalPoolClaim` can be greater than the held claims. However, there is no evidence presented showing accounting problems in the in-scope contracts or demonstrating how the tokens held by the vault could desync from the value in the `state.totalPoolClaim` state variable.

The potential accounting problem would be classified as a future issue, and per Sherlock's judging rules, it should not be considered a valid Medium/High.

https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid

> **Future issues:** Issues that result out of a future integration/implementation that was not intended (mentioned in the docs/README) or because of a future change in the code (as a fix to another issue) are **not** valid issues.

Thus, the recommendation is a defense-in-depth measure to guard against potential accounting errors that might occur in the future.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> There are two (2) possible scenarios outlined in the report:
> 
> 1) If the admin wants to withdraw all shares during an emergency, they should configure the `claimToExit` to zero as per the source code's comment at Line 479 below. If the admin wants to withdraw all shares but chooses not to set the `claimToExit` to zero and results in undesirable consequences, it is considered an admin input error and should not be considered a valid Medium/High.
> 
> ```solidity
> File: SingleSidedLPVaultBase.sol
> 475:     /// @notice Allows the emergency exit role to trigger an emergency exit on the vault.
> 476:     /// In this situation, the `claimToExit` is withdrawn proportionally to the underlying
> 477:     /// tokens and held on the vault. The vault is locked so that no entries, exits or
> 478:     /// valuations of vaultShares can be performed.
> 479:     /// @param claimToExit if this is set to zero, the entire pool claim is withdrawn
> 480:     function emergencyExit(
> 481:         uint256 claimToExit, bytes calldata /* data */
> 482:     ) external override onlyRole(EMERGENCY_EXIT_ROLE) {
> ```
> 
> 2) Following is the extract from the report:
> 
> > To exit all funds, it most likely zero will be used as `claimToExit`, however is still a case where `state.totalPoolClaim` can be greater than the held claims, meaning you would legitimately pass in a non-zero value for `claimToExit`.
> >
> > Accounting problems with either the reward or LP pools (e.g. from an exploit), would result in the claims accounted in the leveraged vaults being no longer in sync with those held by the pools, meaning `claimToExit` would be the value held by the pools, not `state.totalPoolClaim`.
> 
> It stated that this would be an issue if there were an accounting problem within Notional's leverage vault that could result in a case where the `state.totalPoolClaim` can be greater than the held claims. However, there is no evidence presented showing accounting problems in the in-scope contracts or demonstrating how the tokens held by the vault could desync from the value in the `state.totalPoolClaim` state variable.
> 
> The potential accounting problem would be classified as a future issue, and per Sherlock's judging rules, it should not be considered a valid Medium/High.
> 
> https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid
> 
> > **Future issues:** Issues that result out of a future integration/implementation that was not intended (mentioned in the docs/README) or because of a future change in the code (as a fix to another issue) are **not** valid issues.
> 
> Thus, the recommendation is a defense-in-depth measure to guard against potential accounting errors that might occur in the future.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by CjHare** [comment]
Removing concrete numbers from the example, the abstracts steps are:

- Admin (Alice) submits emergency withdrawal transaction with a non-zero amount for `claimToExit` (aliceTx)
- Normal user (Bob) submits their withdrawal (bobTx)
- bobTx is processed before aliceTx, with the standard withdrawal in bobTx changing the holding of the vault
- aliceTx is now processed, but as bobTx changed the vault holdings, the`claimToExit` that was valid when aliceTx was submitted is now too large, reverts the emergency withdrawal transaction


Escalation notes:
1. Assumes that `claimToExit` will always match the external dependencies accounting and there is an implicit requirement that only zero is used for full withdrawal. 

In the scenario of a exploit in the either the reward pool or LP pool where that accounting is affect, the Notional vault could not withdraw their full holdings due to an exploit in that contract, but only perform a partial withdrawal (`claimToExit` would not be the full holdings, but a correct and valid input).

The `EMERGENCY_EXIT_ROLE` is only a `RESTRICTED` role, with the only mention of using zero to claim all holdings being the function comment, where the language presents it as an option, not a explicit requirement that zero be used to claim all.
As a restricted role could be held by an entity other than Notional, and without supporting integration docs clearly stating the expectation of only using `claimToExit` of zero, entering the full holdings as a parameter would be valid input by the `EMERGENCY_EXIT_ROLE`.


2. I’m not sure on this point being made.

The Notional vault keeps a separate record of account with  `StrategyVaultState` to the those held by the external reward pool and LP pools. 
If the external account changes, it follow that the `state.totalPoolClaim` will be desynced (as there’s no syncing operation).

**Comment by xiaoming9090** [comment]
> The EMERGENCY_EXIT_ROLE is only a RESTRICTED role, with the only mention of using zero to claim all holdings being the function comment, where the language presents it as an option, not a explicit requirement that zero be used to claim all.
As a restricted role could be held by an entity other than Notional, and without supporting integration docs clearly stating the expectation of only using claimToExit of zero, entering the full holdings as a parameter would be valid input by the EMERGENCY_EXIT_ROLE.

Regarding the above point, the code's comment mentioned that zero be used to claim all, which is sufficient. Otherwise, in future audit contests, Watsons will argue that the information in the source code's comments is not sufficient as they are not being documented in the official/integration documentation. 

**Scenario 1 - When the caller sets the `claimToExit` to zero to claim all**

`state.totalPoolClaim` represents the number of LP tokens staked at Convex/Aura by the vault. If the vault staked 100 BPT at Aura, the Aura's `balanceOf` function will return 100 BPT, which is in sync with the `state.totalPoolClaim`  under normal circumstances.

The issue described in this report will happen if the number of LP tokens returned from Aura's `balanceOf` function somehow deviates from the 100 BPT staked by the vault (Probably due to an accounting error or exploit at Aura protocol). Let's assume that the Aura's `balanceOf` function returns 90 BPT due to an error or exploit on Aura protocol. When the caller sets the `claimToExit` to zero, the vault will claim `state.totalPoolClaim` LP token from Aura/Convex, which is 100 BPT in this case. When the vault attempts to claim 100 BPT, it will revert.

I will leave it to the judge to decide if an accounting error or exploit in external protocols (Curve/Balancer or Convex/Aura) that integrate with the in-scope protocol should be considered.

**Scenario 2 - When the caller sets the `claimToExit` to a specific value**

In order to DOS the emergency exit, the malicious user of the vault must persistently front-run Notional's emergency exit TX every time without fail, which increases the cost of the attack. To reduce the risk of such front-running, the protocol could submit the emergency exit TX via the private mempool and/or set a high gas price.

**Comment by Czar102** [comment]
I agree with the escalation. Also, the impact, which is revert after frontrunning, does not lead to loss of funds by itself. The properties of this situation are the same as in an AMM slippage check. Also, the functionality exists, as @xiaoming9090 mentioned, that makes proposed addition redundant.

Planning to accept the escalation and consider this invalid.

**Comment by nevillehuang** [comment]
I agree this should be low severity.

1. Does not cause loss of funds
2. Does not cause a permanent DoS, or at least it is extremely non-profitable to do so.

**Comment by Czar102** [comment]
"Persistent frontruns" is not an issue. You can always set the gas price sufficiently high, or use a private mempool. Alternatively, you can submit transactions withdrawing half of your holdings, a quarter, and so on, and this way you will withdraw all your holdings in ~log(your share balance in wei) transactions without fearing about the fact that your number of shares may decrease in between tx submission and execution.

Scenarios concerning which functions breaking will be recoverable and which won't is a design choice. Hence, that's not going to determine the validity of the report.

I still think this submission should be invalid.

**Comment by Czar102** [comment]
Result:
Low
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-10-notional-judging/issues/99/#issuecomment-1842503175): accepted

**Comment by MLON33** [comment]
Fix: https://github.com/notional-finance/leveraged-vaults/pull/65

**Comment by xiaoming9090** [comment]
Fixed in [PR 65](https://github.com/notional-finance/leveraged-vaults/pull/65)
